from __future__ import unicode_literals
import time
import os

AUTHOR = u'Leonardo Uieda'

SITENAME = u'Leonardo Uieda'
SITESUBTITLE = u'Geophysics, inverse problems, science, and software'
SITEURL = ''

# Language and time
DEFAULT_LANG = u'en'
TIMEZONE = u'America/Sao_Paulo'

# This goes at the footer of the site
COPYRIGHT_NOTICE = """
Contents &copy; {date} {author} -
Except where otherwise noted, all content is
avilable under a
<a href="http://creativecommons.org/licenses/by/3.0/legalcode">CC-BY
license</a>
<img class="CCBY" src="/static/images/cc-by.jpg" width="90px">
""".format(author=AUTHOR, date=time.gmtime().tm_year)

# File formats
ARTICLE_URL = 'posts/{date:%Y}-{date:%m}-{date:%d}-{slug}.html'
ARTICLE_SAVE_AS = 'posts/{date:%Y}-{date:%m}-{date:%d}-{slug}.html'

STATIC_PATHS = ['images', 'notebooks']

DEFAULT_PAGINATION = 10
DISPLAY_CATEGORIES_ON_MENU = False

# Feeds
FEED_ALL_RSS = 'rss.xml'
FEED_RSS = None
FEED_ATOM = None
FEED_ALL_ATOM = None
CATEGORY_FEED_ATOM = None

THEME = 'theme/pelican-bootstrap3'

# Top menu
DISPLAY_PAGES_ON_MENU = False
MENUITEMS = [
    ('about', '/about.html'),
    ('github', 'https://github.com/leouieda'),
    ('twitter', 'https://twitter.com/leouieda'),
    ('google+', 'https://plus.google.com/+LeonardoUieda'),
    ('linkedin', 'http://www.linkedin.com/in/uieda'),
    ('figshare', 'http://figshare.com/authors/Leonardo%20Uieda/97471'),
    ('orcid', 'http://orcid.org/0000-0001-6123-9515'),
    ('rss', '/rss.xml'),
]

PLUGIN_PATH = os.path.join(os.environ.get('HOME'), 'src/pelican-plugins')
# Include plugins by jakevdp. See the PR for examples
# (https://github.com/getpelican/pelican-plugins/pull/21)
PLUGINS = ['summary', 'liquid_tags.video', 'liquid_tags.include_code',
           'liquid_tags.notebook']

# This header file is automatically generated by the notebook plugin
# (copied shamelessly from
# https://github.com/jakevdp/PythonicPerambulations/blob/master/pelicanconf.py)
if not os.path.exists('_nb_header.html'):
    import warnings
    warnings.warn("_nb_header.html not found. "
                  "Rerun make html to finalize build.")
else:
    with open('_nb_header.html') as f:
        EXTRA_HEADER = f.read().decode('utf-8')



